USE hr;

SELECT * FROM employees WHERE ADDRESS LIKE '%Elgin,IL';

SELECT * FROM employees WHERE B_DATE LIKE '197%';

SELECT * FROM employees WHERE DEP_ID = 5 AND SALARY BETWEEN 60000 AND 70000;

SELECT * FROM employees ORDER BY DEP_ID;

SELECT * FROM employees 
ORDER BY DEP_ID DESC, L_NAME DESC;

SELECT DEP_ID, COUNT(*) AS EmployeeCount
FROM employees
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, ROUND(AVG(SALARY),2) AS AVG_SALARY
FROM employees
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, ROUND(AVG(SALARY),2) AS AVG_SALARY
FROM employees
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;
